[package]
name = "findutils"
version = "0.2.0"
homepage = "https://github.com/uutils/findutils"
repository = "https://github.com/uutils/findutils"
edition = "2018"
license = "MIT"
readme = "README.md"
description = "Rust implementation of GNU findutils"
authors = ["uutils developers"]

[dependencies]
glob = "0.3"
walkdir = "2.3"
tempfile = "3"
regex = "1.7"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
serial_test = "0.5"

[[bin]]
name = "find"
path = "src/find/main.rs"

[[bin]]
name = "testing-commandline"
path = "src/testing/commandline/main.rs"
